### ISSUE TITLE
Layout broken for web on mobile

### ISSUE THREAD

**Issue by lackrobin** [Tunnelsats/tunnelsats#91]
![Screenshot_20230103-105027](https://user-images.githubusercontent.com/7565918/210297899-a9c6f6c1-e711-4a9c-80b6-15d0412989e2.png)

It seems like the Nav-Bar breaks the layout on mobile.

__possible fix:__ moving the navbar items into  a dropdown when on mobile

**Comment by blckbx** [comment]
Thanks for reporting! Yes, mobile view has been neglected lately. I'll have a look into your proposal.
